trigger:
  branches:
    include:
      - main
      - feature/*

pool: agent-ka-pool   # Tumhara Windows agent

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: 'Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/module'
    backendServiceArm: 'servocon'
    backendAzureRmStorageAccountName: 'strgaccyaml'
    backendAzureRmContainerName: 'cntryaml'
    backendAzureRmKey: 'new.tfstate'

- task: TerraformTask@5
  displayName: 'Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/module'
    environmentServiceNameAzureRM: 'servocon'

# ✅ Install Python manually on Windows agent
- powershell: |
    Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.10.11/python-3.10.11-amd64.exe -OutFile python-installer.exe
    Start-Process python-installer.exe -ArgumentList "/quiet InstallAllUsers=1 PrependPath=1 Include_pip=1" -Wait
    python --version
    pip --version
  displayName: 'Install Python & pip (Windows)'

# 🔒 Run Checkov security scan
- powershell: |
    pip install checkov
    checkov -d $(System.DefaultWorkingDirectory)/module --quiet --compact
  displayName: 'Run Security Scan (Checkov)'

- task: TerraformTask@5
  displayName: "Terraform Apply (only after merge to main)"
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/module'
    environmentServiceNameAzureRM: 'servocon'
