trigger:
  branches:
    include:
      - main         # merge ke baad chalega (apply bhi hoga)
      - feature/*    # feature branches pe bhi chalega (sirf plan tak)

pool: agent-ka-pool

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: 'Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/module'
    backendServiceArm: 'servocon'
    backendAzureRmStorageAccountName: 'strgaccyaml'
    backendAzureRmContainerName: 'cntryaml'
    backendAzureRmKey: 'new.tfstate'

- task: TerraformTask@5
  displayName: 'Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/module'
    environmentServiceNameAzureRM: 'servocon'

# ✅ Install Python (pip included)
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

# 🔒 Run Security Scan with Checkov
- script: |
    pip install checkov
    checkov -d $(System.DefaultWorkingDirectory)/module --quiet --compact
  displayName: 'Run Security Scan (Checkov)'

- task: TerraformTask@5
  displayName: "Terraform Apply (only after merge to main)"
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/module'
    environmentServiceNameAzureRM: 'servocon'
