trigger:
  branches:
    include:
      - main
      - feature/*
    
pr: none

pool: agent-ka-pool

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/module'
    backendServiceArm: 'servocon'
    backendAzureRmStorageAccountName: 'strgaccyaml'
    backendAzureRmContainerName: 'cntryaml'
    backendAzureRmKey: '24.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/module'
    environmentServiceNameAzureRM: 'servocon'

# ✅ Apply will only run if the branch is main (i.e., PR is merged)
- task: TerraformTask@5
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/module'
    environmentServiceNameAzureRM: 'servocon'
