trigger:
  branches:
    include:
      - main         # merge ke baad chalega (apply bhi hoga)
      - feature/* 

pool: agent-ka-pool   # tumhara self hosted agent

steps:
# Install Terraform
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

# Terraform Init
- task: TerraformTask@5
  displayName: 'Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/module'
    backendServiceArm: 'servocon'
    backendAzureRmStorageAccountName: 'strgaccyaml'
    backendAzureRmContainerName: 'cntryaml'
    backendAzureRmKey: 'new.tfstate'

# Terraform Plan
- task: TerraformTask@5
  displayName: 'Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/module'
    environmentServiceNameAzureRM: 'servocon'

# Install tfsec (via Chocolatey)
- powershell: |
    choco install tfsec -y
  displayName: 'Install tfsec'

# Run Security Scan with tfsec
- powershell: |
    tfsec $(System.DefaultWorkingDirectory)/module
  displayName: 'Run Security Scan (tfsec)'

# Terraform Apply (only after merge to main)
- task: TerraformTask@5
  displayName: "Terraform Apply (only after merge to main)"
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/module'
    environmentServiceNameAzureRM: 'servocon'
