trigger:
  branches:
    include:
      - main         # merge ke baad chalega (apply bhi hoga)
      - feature/*

pool: agent-ka-pool

steps:
# 1️⃣ Install Terraform
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

# 2️⃣ Terraform Init
- task: TerraformTask@5
  displayName: 'Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/module'
    backendServiceArm: 'servocon'
    backendAzureRmStorageAccountName: 'strgaccyaml'
    backendAzureRmContainerName: 'cntryaml'
    backendAzureRmKey: 'new.tfstate'

# 3️⃣ Terraform Plan
- task: TerraformTask@5
  displayName: 'Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/module'
    environmentServiceNameAzureRM: 'servocon'

# 4️⃣ Install Python + Checkov (only if not installed on agent)
- powershell: |
    Write-Host "Installing Python & Checkov..."
    if (-not (Get-Command python -ErrorAction SilentlyContinue)) {
        Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.10.11/python-3.10.11-amd64.exe -OutFile python-installer.exe
        Start-Process python-installer.exe -ArgumentList '/quiet InstallAllUsers=1 PrependPath=1 Include_pip=1' -Wait
    }
    python --version
    pip install --upgrade pip
    pip install checkov
  displayName: 'Install Python & Checkov'

# 5️⃣ Run Checkov Scan
- script: |
    checkov -d $(System.DefaultWorkingDirectory)/module --quiet --compact
  displayName: 'Run Security Scan (Checkov)'

# (Optional) 👉 Agar tum tfsec use karna chahte ho
# - powershell: |
#     choco install tfsec -y
#     tfsec $(System.DefaultWorkingDirectory)/module
#   displayName: 'Run Security Scan (tfsec)'

# 6️⃣ Terraform Apply (only on main)
- task: TerraformTask@5
  displayName: "Terraform Apply (only after merge to main)"
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/module'
    environmentServiceNameAzureRM: 'servocon'
